### ISSUE TITLE
SharedArrayBuffer is not defined - Firefox

### ISSUE THREAD

**Issue by kwadroke** [exokitxr/exokit-web#1]
Error in Console: `ReferenceError: SharedArrayBuffer is not defined` in Mozilla Firefox 68.0.2 (Desktop)

Per Mozilla SharedArrayBuffer is disabled in Firefox due to Spectre, but, re-enabled in Chrome since ~v67
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

I figure that the target would be Google Chrome based browsers, but, wanted to a report Firefox issue.

**Comment by modulesio** [comment]
Labeling this is `wontfix` for now. The plan is to wait for Firefox to fix their `SharedArrayBuffer` implementation.

**Comment by RangerMauve** [comment]
@kwadroke Was enabling the shared buffers flag all you needed to do to get it to load? I still had those uncaught exceptions from before in Nightly.

**Comment by modulesio** [comment]
We aren't using import in Worker anymore if that's the question.

**Comment by RangerMauve** [comment]
Oh sweet. After pulling the latest master it seems to be working! :D :D

**Comment by kwadroke** [comment]
It's working pulling from master on FF 68.0.2 Desktop (non-VR mode) after enabling `javascript.options.shared_memory` without building. Will test on 69 once I restart FF.

**Comment by chrisplatorres** [comment]
Working for me on FF 70.0b3 (64-bit) and FF 69.0 (64-bit)

after `javascript.options.shared_memory` enabled

**Comment by kwadroke** [comment]
Tested on FF 69 Desktop with `javascript.options.shared_memory` and so far it works. Closing Issue.

**Comment by kwadroke** [comment]
For historical/search purposes:
SharedArrayBuffer work-around is no longer needed by Commit 643da0b (pull Request #47) .
