### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#10]
We should write up docs for how `<xr-iframe>` works and how to boot an engine instance into the browser.

**Comment by modulesio** [comment]
This should probably also cover any browser incompatibility and entering into XR with an Origin Trial.

**Comment by chrisplatorres** [comment]
Reality Tabs are `xr-iframes` which are like `iframes` but will extra spatial attributes like `position`, `scale`, `orientation`

## Top-level creation
```js
  // Import exokit-web
  import('https://web.exokit.org/src/index.js'))
  .then(() => {
    // Create xr-iframe, define src attribute, and append to body
    const xrIframe = document.createElement('xr-iframe');
    xrIframe.src = 'child.html';
    document.body.appendChild(xrIframe);
  });
```

## xr-iframe manipulation

```js
  // Set xr-iframe position
  xrIframe.position = [1, 1, 1];
  // Set xr-iframe orientation
  xrIframe.orientation = new THREE.Quaternion().setFromEuler(new THREE.Euler(1, 1, 1, 'YXZ')).toArray();
  // Set xr-iframe scale
  xrIframe.scale = [1, 1, 1];
```

## Child xr-iframe creation

```js
  // Create WebGL renderer and define layers
  const renderer = new THREE.WebGLRenderer({
    antialias: true,
  });
  document.body.appendChild(renderer.domElement);
  const layers = [renderer.domElement];

...

  // Request WebXR session and assign session layers
  const session = await navigator.xr.requestSession({
    exclusive: true,
  });
  session.layers = layers;

...

  // Create xr-iframe, define src attribute, and push to layers
  xrIframe = document.createElement('xr-iframe');
  xrIframe.src = 'childschild.html';
  layers.push(xrIframe);
```

**Comment by modulesio** [comment]
> import('https://web.exokit.org/src/index.js'))

We'll need a better URL here if we don't want it to break for people.

**Comment by modulesio** [comment]
> // Create xr-iframe, define src attribute, and append to body

We should say that this uses shadow dom and behaves like a `<canvas>`, so you can place it wherever you want as if it were one.

**Comment by modulesio** [comment]
Maybe also a high-level explanation of what's running inside the engine and what's running outside.

It's almost exactly like React where there is a bootstrap code and then the actual rendering is controlled by the engine itself.

**Comment by chrisplatorres** [comment]
Should put something about #1 for Firefox users, the issue is fixed by in `about:config` enabling `javascript.options.shared_memory`

**Comment by modulesio** [comment]
This is being covered in https://github.com/exokitxr/exokit-web-docs.
