### ISSUE TITLE
Update boilerplate example code

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#102]
Update examples to use `xr-site`

![0simple1Capture](https://user-images.githubusercontent.com/29695350/65193624-54af1300-da41-11e9-90ca-a9af6336deee.png)

**Comment by modulesio** [comment]
We should probably also document `<xr-site>` itself since that's a new concept.

**Comment by modulesio** [comment]
I'm holding off on documenting this one until `<xr-site>` transclusions work seamlessly, inside `<xr-iframe>` children as well as the browser.
