### ISSUE TITLE
Transform/Rotate/Scale gizmo

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#115]
The current transformControl allows for changing of the current position, but we could include the `orientation`/rotation and `scale`ing abilities.

**Comment by madjin** [comment]
Can the transformControls be toggled with keys similar to spoke/unity as default?
- `w` for move
- `e` for rotate
- `r` for scale

**Comment by modulesio** [comment]
![lol8](https://user-images.githubusercontent.com/6926057/65661586-0204c680-e000-11e9-8cdd-25768f045754.gif)

**Comment by modulesio** [comment]
Also added sensitivity support for the rotation/scale transforms; can be changed with `1234`.
