### ISSUE TITLE
Hubs loading stuck in room lobby

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#12]
Loading a hubs URL: https://hub.link/GQpemja  /  https://hubs.mozilla.com/GQpemja/petty-sturdy-room does not enter the room and is stuck in the lobby.

![hubsloadingwCapture](https://user-images.githubusercontent.com/29695350/64283737-a32ac080-cf1d-11e9-9ecb-1446283f094d.PNG)

**Comment by modulesio** [comment]
Was this with the forced entry?

**Comment by modulesio** [comment]
Also is this projection correct? It looks like the matrix and/or the viewport is wrongly sized.

**Comment by modulesio** [comment]
As far as I can tell this one was using the wrong URL during testing.
