### ISSUE TITLE
Rename top frame to xr-scene

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#23]
There are basically two xr-iframe elements right now: the top one and all child ones.

The top one is used to bootstrap Exokit Engine, and the child ones are reality tabs. We should give them distinct names accordingly.

A reasonable name for the top element seems xr-scene, since it contains the rest of exokit.

**Comment by chrisplatorres** [comment]
Updated documentation at https://github.com/exokitxr/exokit-web-docs/commit/b3f10ac596f0320f30a5dee9101ca5270d30eb20.
