### ISSUE TITLE
Stop rotation on demo

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#25]
The demo is super annoying right now, since it rotates while the user is trying to twiddle the gizmos.

This is also potentially hiding gizmo mouse event alignment bugs.

**Comment by chrisplatorres** [comment]
Should there be an orbitControl setup instead?

**Comment by modulesio** [comment]
It could be, but note that on our _other_ project the way it works I think required hacks to have the two not conflict.

**Comment by modulesio** [comment]
Fixed.
