### ISSUE TITLE
XR device testing

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#26]
Should test these devices to make sure the WebXR implementation is working:

- [x] Oculus Quest
- [x] Magic Leap 
- [x] Android
- [x] StreamVR Vive-style
- [x] SteamVR Oculus Rift
- [x] iPhone --  tried chrome + safari on ios and both don't work -- https://github.com/exokitxr/exokit-web/issues/28#issuecomment-529054479
- [x] MacOS

This includes the 2D page rendering, as well as XR entry: https://github.com/exokitxr/exokit-web/issues/13

**Comment by chrisplatorres** [comment]
Result on Oculus Browser on Quest. Will need to resize/hide the UI based on browser window size. Could use same as #28 

![com oculus vrshell-20190905-153417](https://user-images.githubusercontent.com/29695350/64378683-d4c18b80-cff2-11e9-93f8-3489ddb71da1.jpg)

**Comment by modulesio** [comment]
Clarified that we should also be testing XR entry. That would probably block this issue on https://github.com/exokitxr/exokit-web/issues/13.

**Comment by chrisplatorres** [comment]
#13 XR entry button is not entering in Oculus Browser on the Oculus Quest.

**Comment by modulesio** [comment]
@chrisplatorres Any way to get a log?

**Comment by chrisplatorres** [comment]
Yes:

 how to wirelessly do dev tools:

**Quest plugged in**
- `adb shell ip route `
ip address is `src`

- `adb tcpip 5555`
**Quest unplugged**
- `adb connect ip:5555`

- in chrome `chrome://inspect`
- open site in quest

this worked on linux, windows was having some firewall issues:
`An attempt was made to access a socket in a way forbidden by its access permissions. (10013)`

**Comment by chrisplatorres** [comment]
Tested and found that Magic Leap does not allow `SharedArrayBuffer` (#43) and does not have a flag to enable.

**Comment by chrisplatorres** [comment]
pixel3a / android by default gives error

`Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined`

but it works after enabling chrome://flags -> sharedarraybuffer experimental flag

![Screenshot_20190905-234457](https://user-images.githubusercontent.com/29695350/64401623-520eef80-d037-11e9-8da5-14612fdebbed.png)

**Comment by chrisplatorres** [comment]
Current Oculus Quest / Oculus Browser error, with WebVR/WebXR flags enabled:

`com.oculus.browser (OculusBrowser/6.0.17.167158974 SamsungBrowser/4.0 Chrome/74.0.3729.182)`

![questlogCapture](https://user-images.githubusercontent.com/29695350/64447829-e2821a00-d0a1-11e9-95ce-e0bbac594c1f.PNG)

**Comment by modulesio** [comment]
That error is WebXR not being supported by Quest right? The flags should be disabled do the poly fill takes over.

**Comment by chrisplatorres** [comment]
Getting similar error on desktop SteamVR:
![xrsteamvrerrorCapture](https://user-images.githubusercontent.com/29695350/64457130-727e8e80-d0b7-11e9-8ef7-b0936ca2c6be.PNG)

**Comment by chrisplatorres** [comment]
Getting this error on Chrome Canary with the following flag setup:
![canar2Capture](https://user-images.githubusercontent.com/29695350/64458486-1584d780-d0bb-11e9-8cb0-9206ec006207.PNG)
![canarCapture](https://user-images.githubusercontent.com/29695350/64458487-1584d780-d0bb-11e9-92d3-340bb5ffe69c.PNG)

**Comment by chrisplatorres** [comment]
Error when attempting to disable WebXR flags and load web.exokit.org 's polyfill (note: polyfill did work on WebXR samples): 

![com oculus vrshell-20190906-154821](https://user-images.githubusercontent.com/29695350/64459742-3dc20580-d0be-11e9-9c0f-47bf6e7690eb.jpg)
![chrquest](https://user-images.githubusercontent.com/29695350/64459743-3dc20580-d0be-11e9-92b7-e07ee3c96e90.PNG)

**Comment by chrisplatorres** [comment]
`navigator.xr` is undefined on web.exokit.org, but logs as the polyfill in the samples:

![xrnavCapture](https://user-images.githubusercontent.com/29695350/64459855-92658080-d0be-11e9-9e79-303f86869dbb.PNG)

**Comment by modulesio** [comment]
MLO testing: https://github.com/exokitxr/exokit-web/pull/47#issuecomment-529016595

**Comment by chrisplatorres** [comment]
Loading in MLO now, but when clicking the XR entry button, getting similar error as Quest:

> xr-scene.js:141 Uncaught (in promise) TypeError: Failed to execute 'requestSession' on 'XR': cannot convert to dictionary.

![mlo2Capture](https://user-images.githubusercontent.com/29695350/64461259-53d1c500-d0c2-11e9-881e-81244ec511dd.PNG)

**Comment by chrisplatorres** [comment]
### Magic Leap

Magic Leap is loading without an issue now, other than the white grid is visually weird in AR because it goes out to infinity/does not depth clip with IRL environment. Also a-blaster is "stuck to your face" / not updating position or anything:
![ablastCapture](https://user-images.githubusercontent.com/29695350/64479325-e7ff6300-d17a-11e9-8a85-550ebb2bc09e.PNG)

----------------------------------------

### Oculus Quest
  
Oculus Quest is loading now and there is no longer any "tracer" bug. A-Painter loads and paints correctly. Moon Rider is play-able:

![com oculus browser-20190907-143139](https://user-images.githubusercontent.com/29695350/64479458-f3538e00-d17c-11e9-8a96-2ff5ba7f6f6d.jpg)



A-Blaster does not load:
  
![qablasCapture](https://user-images.githubusercontent.com/29695350/64479449-d028de80-d17c-11e9-96ab-bc6928544355.PNG)
![2qablasCapture](https://user-images.githubusercontent.com/29695350/64479450-d15a0b80-d17c-11e9-8e0f-701fe550133a.PNG)

**Comment by modulesio** [comment]
We could use the MLO log for the html UI loading. Otherwise we can’t put in any html ui for the demo.

**Comment by chrisplatorres** [comment]
MLO log for html UI, still showing the plane as black.

![mlooCapture](https://user-images.githubusercontent.com/29695350/64587674-b72f5180-d365-11e9-8775-67e74e5948a5.PNG)

**Comment by modulesio** [comment]
The ML1 case should be fixed + rendering fine now.

**Comment by modulesio** [comment]
iPhone works in cardboard mode. We can explore `immersive-ar` mode on iOS in the future.

**Comment by modulesio** [comment]
I think think means we have parity across browsers, so closing this one 🎸.
