### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#27]
Added all requirements for:

- Desktop
- Quest
- Android phone chrome
- Desktop Firefox HTC Vive/OpenVR VR
- Desktop Chrome HTC Vive/OpenVR VR
- Magic Leap One / Helio

Will also need:
- [x] iOS
- [x] Oculus Desktop VR Chrome
- [x] Oculus Desktop VR Firefox
- [x] Oculus Go Firefox Reality
- [x] MacOS
- [x] Oculus Quest Firefox Reality
- [x] Oculus Go Oculus Browser
- [ ] ~~Desktop Supermedium~~ -- not loading, can't debug

We should also note the requirements and flag setup for the above in the docs.

**Comment by chrisplatorres** [comment]
Firefox flag requirement:

Enable `javascript.options.shared_memory` through `about:config`

**Comment by modulesio** [comment]
☝️ That should probably go on the docs pages. I'll open an issue over in that repo.

**Comment by chrisplatorres** [comment]
None of the Firefox browsers support webxr yet, but that work is in progress: https://bugzilla.mozilla.org/show_bug.cgi?id=1419190

https://immersive-web.github.io/webxr-reference/webxr-device-api/compatibility.html

**Comment by chrisplatorres** [comment]
Flags required for Chrome WebXR entry: https://github.com/exokitxr/exokit-web-docs/issues/4#issuecomment-529046600

![image](https://user-images.githubusercontent.com/29695350/64480975-d462f500-d198-11e9-956f-db999104ca71.png)

**Comment by chrisplatorres** [comment]
Noted the device testing left to put into docs here: https://github.com/exokitxr/exokit-web-docs/issues/4

Updated OP.

**Comment by modulesio** [comment]
I don't know about MacOS VR; I'm not set up for that and I've never seen it work.

MacOS does work in desktop mode though.

**Comment by chrisplatorres** [comment]
Works on Firefox Reality with Oculus Quest

**Comment by modulesio** [comment]
MacOS Safari error:

```
[Warning] No DPDB device match. (webxr-polyfill.module.js, line 3815)
[Error] Failed to recalculate device parameters.
	recalculateDeviceParams_ (webxr-polyfill.module.js:3767)
	Dpdb (webxr-polyfill.module.js:3738)
	CardboardVRDisplay (webxr-polyfill.module.js:5008)
	CardboardXRDevice (webxr-polyfill.module.js:6014)
	(anonymous function) (webxr-polyfill.module.js:6056)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Warning] Using fallback Android device measurements. (webxr-polyfill.module.js, line 3551)
[Error] TypeError: function is not a constructor (evaluating 'super()')
	WorkerVm (WindowVm.js:29)
	_makeWindow (WindowVm.js:250)
	_onnavigate (xr-scene.js:37)
	attributeChangedCallback (xr-scene.js:122)
	setAttribute
	src (xr-scene.js:134)
	(anonymous function) (web.exokit.org:194)
	asyncFunctionResume
	promiseReactionJob
[Log] xr available (web.exokit.org, line 213)
```

Presumably this is the same error holding up iPhone.

**Comment by modulesio** [comment]
The error is that `new EventTarget` is not classy in Safari, though it is classy everywhere else. We use it in inheritance.

**Comment by modulesio** [comment]
https://github.com/mysticatea/event-target-shim

**Comment by modulesio** [comment]
We can use that shim and test for `/safari/i.test(navigator.userAgent) && !/chrome/i.test(navigator.userAgent)`.

**Comment by modulesio** [comment]
I think all of the browsers work now 🎉.
