### ISSUE TITLE
SharedArrayBuffer revisit

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#43]
Android, Firefox Desktop, Oculus Quest, and Magic Leap appear to not support SAB in their public releases at the moment.

Most of these have (somewhat annoying) flag overrides, but Magic Leap does not.

Therefore it makes sense to revisit a slow re-implementation of buffer sharing across workers.

**Comment by modulesio** [comment]
Previous issue: #1.

**Comment by chrisplatorres** [comment]
Fixed by #47
