### ISSUE TITLE
In-XR Locomotion

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#52]
Perhaps there should be a way to move around the world, both in 2d (orbit controls) and in XR. The reason why this might **not** be worth doing is because this is just to serve as a demo and not an actual way of managing and experiencing reality tabs.

**Comment by modulesio** [comment]
Yeah, I would put that into our “frontend”, not an examples page.

**Comment by chrisplatorres** [comment]
Moved.
