### ISSUE TITLE
xr-iframe deletion ability

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#53]
Perhaps we should allow for deleting xr-iframes that have been opened. The reason why this might **not** be worth doing is because this is just to serve as a demo and not an actual way of managing and experiencing reality tabs.

**Comment by modulesio** [comment]
I think it’s fine to have select and delete in this index.html.

Actually that is probably a good thing to have available for testing, aside from any ui.

**Comment by modulesio** [comment]
Added in `index.html`.

![Capture 50](https://user-images.githubusercontent.com/6926057/64579887-7712a380-d352-11e9-8e06-3eabf1db3672.PNG)
