### ISSUE TITLE
In-XR example opening and deletion UI

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#54]
Perhaps there should be an in-XR UI for opening and deleting xr-iframes/sites. The current setup requires spawning from 2d and then going into XR.

The reason why this might **not** be worth doing is because this is just to serve as a demo and not an actual way of managing and experiencing reality tabs.

**Comment by modulesio** [comment]
If we do this I think we should just demo our html ui in xr capability and render the examples list.

An actual ui to be used would be a different project.

**Comment by modulesio** [comment]
Closing in favor of https://github.com/exokitxr/exokit-web/issues/65.
