### ISSUE TITLE
Default tutorial xr-iframe causing darkness

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#56]
The default tutorial.html xr-iframe causing darkness/blackness when pushed to layers:

### Commented `// layers.push(tutorialXrIframe);`

![grid002Capture](https://user-images.githubusercontent.com/29695350/64480925-68cc5800-d197-11e9-862a-f2ad92974267.PNG)

### Un-commented `layers.push(tutorialXrIframe);`
![grid00Capture](https://user-images.githubusercontent.com/29695350/64480926-68cc5800-d197-11e9-871d-46caae2f3369.PNG)

**Comment by modulesio** [comment]
What is the list of layers without this?

**Comment by chrisplatorres** [comment]
Commented out:
layers = [object HTMLCanvasElement]

uncommented (darkness):
layers = [object HTMLCanvasElement],[object HTMLElement]
