### ISSUE TITLE
Hubs loading

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#57]
Related to https://github.com/exokitxr/exokit/issues/810 / https://github.com/exokitxr/exokit-web/issues/12 , Hubs "loads", asks for mic permissions in Chrome, and plays entry sound effect, but just has a texture that is "stuck" to the camera view.

### Link used

https://hubs.mozilla.com/GQpemja/petty-sturdy-room?vr_entry_type=vr_now

### Screenshot

![hubswebsCapture](https://user-images.githubusercontent.com/29695350/64481047-c8c3fe00-d199-11e9-8537-07be90830fdb.PNG)

**Comment by modulesio** [comment]
What's the full log here?

**Comment by chrisplatorres** [comment]
![hubslogCapture](https://user-images.githubusercontent.com/29695350/64481084-83ec9700-d19a-11e9-80a1-f4c4801333cb.PNG)

**Comment by modulesio** [comment]
Looks like the loading hijack didn't kick in.

**Comment by modulesio** [comment]
There are some GL errors to fix here, though I think the entry is a separate issue. It loads up fine but draws the scene as if you hadn't entered.

**Comment by modulesio** [comment]
Should be fixed now.
