### ISSUE TITLE
Cryptovoxels stereo in mono

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#59]
Cryptovoxels loads, but does not update position when moving around.

**Comment by modulesio** [comment]
Should be working fine now. The bug is that it is loading in stereo even when it shouldn't.

**Comment by modulesio** [comment]
Renamed the issue accordingly.

**Comment by modulesio** [comment]
![Capturelol](https://user-images.githubusercontent.com/6926057/64481759-04b68d80-d1b1-11e9-93e4-66a53386d854.PNG)
