### ISSUE TITLE
Enter XR/No XR button set before polyfill navigator.xr loaded

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#62]
With the Enter XR/No XR button, it is showing "no XR" for me, even though it can enter XR w/ the polyfill
 
At the time of assignment of `result`, `navigator.xr` is undefined, but after page loads, `navigator.xr` is showing the polyfill

https://github.com/exokitxr/exokit-web/compare/8e055a2cad...33683da914#diff-eacf331f0ffc35d4b482f1d15a887d3bR248

**Comment by modulesio** [comment]
Might be fixed with https://github.com/exokitxr/exokit-web/commit/30e296f7a4f80200dcaf3786bdbb628628031d46.

**Comment by modulesio** [comment]
I _think_ this is fixed.

@chrisplatorres can you close if not?

**Comment by chrisplatorres** [comment]
Fixed.
