### ISSUE TITLE
In-XR gizmo control

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#64]
The Gizmo currently cannot be manipulated from XR, but that would be a useful demo feature.

Note the browser already has a much more complete version of reality tabs placement, but the demo page does not.

**Comment by modulesio** [comment]
Moving this to the "browser" flavor.

**Comment by chrisplatorres** [comment]
I think the Viewer demo should remain minimal since anyone who wants to have an in-XR xr-iframe manipulation could use the Exokit Browser.
