### ISSUE TITLE
In-XR HTML UI 

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#65]
We have an HTML UI at the top-level `index.html`, but with `exokit-render` we could put it into XR as well.

This could include the reality tabs open/close UI.

**Comment by modulesio** [comment]
Moving this to the "browser" flavor.

**Comment by chrisplatorres** [comment]
I think the Viewer demo should remain minimal since anyone who wants to have an in-XR menu could use the Exokit Browser.
