### ISSUE TITLE
transformControls do not distringuish between sites

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#67]
The first two sites opened will share the same transformControl

![hhubscvv](https://user-images.githubusercontent.com/29695350/64585762-99f78480-d35f-11e9-8fb8-772ca9c611ce.PNG)

**Comment by modulesio** [comment]
I think this is only because they are on top of each other

**Comment by chrisplatorres** [comment]
Oops, that was it.

**Comment by modulesio** [comment]
I randomized the site opens a bit now so they will less obviously collide like that by default.
